### ISSUE TITLE
如何使用opengl渲染一张10bit的avif的hdr图片呢

### ISSUE THREAD

**Issue by jingyaxie** [JonaNorman/GLRenderClient#1]
全网好像还没有在android平台渲染hdr图片的解决方案，大神，你能给出一个解决方案吗？

**Comment by JonaNorman** [comment]
有个思路可以参考一下，不一定对
先解码出16bit或者10位的数据，然后用opengl传到texture上(格式写对，RGBA_F16之类的)，然后windowSurface还要开启PQ属性表示展示HDR的PQ图片

**Comment by jingyaxie** [comment]
> 到
对于hdr图片渲染我还有一些不明白的是，渲染的sdr屏幕上的时候需要自己处理tone mapping吗，渲染到不同亮度和色域范围的屏幕上这个还需要自己动态处理映射吗？

**Comment by JonaNorman** [comment]
> > 到
> > 对于hdr图片渲染我还有一些不明白的是，渲染的sdr屏幕上的时候需要自己处理tone mapping吗，渲染到不同亮度和色域范围的屏幕上这个还需要自己动态处理映射吗？

如果是SDR屏幕需要的，如果是HDR屏幕不需要

**Comment by JonaNorman** [comment]
> 全网好像还没有在android平台渲染hdr图片的解决方案，大神，你能给出一个解决方案吗？

刚发现androidx里面有一个heifwriter可以参考一下，希望能帮到你
https://github.com/androidx/androidx/tree/androidx-main/heifwriter/heifwriter/src/main/java/androidx/heifwriter
